
By default, the extension will process every OpenAPI specification file in the given path.
To limit code generation to only a specific set of OpenAPI specification files, you can set the `quarkus.openapi-generator.codegen.include` property.

For instance, if you want to limit code generation for `include-openapi.yaml` and `include-openapi-2.yaml` files, you need to define the property like:

[source,properties]
----
quarkus.openapi-generator.codegen.include=include-openapi.yaml,include-openapi-2.yaml
----

If you prefer to specify which files you want to skip, you can set the `quarkus.openapi-generator.codegen.exclude` property.
For instance, if you want to skip code generation for `exclude-openapi.yaml` and `exclude-openapi-2.yaml` files, you need to define the property like:

[source,properties]
----
quarkus.openapi-generator.codegen.exclude=exclude-openapi.yaml,exclude-openapi-2.yaml
----

IMPORTANT: `exclude` supersedes `include`, meaning that if a file is in both property it will NOT be analysed.

See the module `integration-tests/ignore` for an example of how to use this feature.