By default, this extension generates the methods according to their returning models based on the https://spec.openapis.org/oas/v3.1.0#schema-object[OpenAPI specification Schema Object]. If no response model is defined, `jakarta.ws.rs.core.Response` is returned.

If you want to return `jakarta.ws.rs.core.Response` in _all_ cases instead, you can set the `return-response` property to `Response` or `true`.

== Global configuration

You can set `return-response` **globally** to apply it to all your OpenAPI specifications at once, without repeating the configuration for each spec. The per-spec value takes precedence over the global value.

[source,properties]
----
quarkus.openapi-generator.codegen.return-response=true
----

== Per-spec configuration

Given you want to return `jakarta.ws.rs.core.Response` for the `my-openapi.yaml` file, you must add the following to your `application.properties` file:

[source,properties]
----
quarkus.openapi-generator.codegen.spec.my_openapi_yaml.return-response=true
----

If you want to return `org.jboss.resteasy.reactive.RestResponse` in _all_ cases instead, you can set the `return-response` property to `RestResponse`.

== Per-spec configuration with RestResponse

Given you want to return `org.jboss.resteasy.reactive.RestResponse` for the `my-openapi.yaml` file, you must add the following to your `application.properties` file:

[source,properties]
----
quarkus.openapi-generator.codegen.spec.my_openapi_yaml.return-response=RestResponse
----
