---
openapi: 3.0.3
info:
  title: Hello API
  version: "1.0"
paths:
  /hello:
    get:
      tags:
        - Hello Resource
      operationId: hello
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
