version: 2
updates:
  # Maven updates for main branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"

  # GitHub Actions updates for main branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    
