#!/usr/bin/env bash
set -e

# update the versions
mvn -nsu --settings .github/quarkus-ecosystem-maven-settings.xml -B versions:set-property -Dproperty=quarkus.version -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false -ntp
mvn -nsu --settings .github/quarkus-ecosystem-maven-settings.xml -B versions:set-property -Dproperty=version.io.quarkus -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false -ntp

# run the tests
# resteasy-classic is activated by default
mvn -nsu --settings .github/quarkus-ecosystem-maven-settings.xml -B clean install --fail-at-end -e -ntp
mvn -nsu --settings .github/quarkus-ecosystem-maven-settings.xml -B clean install -Presteasy-reactive --fail-at-end -e -ntp
