# LGTM Settings (https://lgtm.com/)
# For reference, see https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
# or template at https://lgtm.com/static/downloads/lgtm.template.yml

extraction:
  java:
    index:
      maven:
        version: "3.8.4"
      # Specify the Java version required to build the project
      java_version: "17"