quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.spec=rest-response.json
quarkus.openapi.generator.server.base-package=org.acme
quarkus.openapi.generator.server.use-rest-response=true
