openapi: 3.0.2
info:
  title: Simple OpenAPI
  version: 0.0.1-SNAPSHOT
paths:
  /users:
    get:
      responses:
        "400":
          description: "Success"
          content:
            "application/json":
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "John Doe"