package io.quarkiverse.openapi.generator.providers;

import java.util.List;

import jakarta.ws.rs.client.ClientRequestContext;
import jakarta.ws.rs.client.ClientRequestFilter;

/**
 * Authentication Provider for {@link ClientRequestFilter}s generated by the extension.
 */
public interface AuthProvider extends ClientRequestFilter {

    /**
     * Get the name of the Security Provider as defined in the OpenAPI Spec file.
     *
     * @see <a href="https://spec.openapis.org/oas/v3.1.0#security-requirement-object">OpenAPI Spec - Security Requirement
     *      Object</a>
     */
    String getName();

    List<OperationAuthInfo> operationsToFilter();

    /**
     * Called when a request handled by this provider receives a {@code 401 Unauthorized} response.
     * Providers that support refreshing stale credentials on demand (e.g. OAuth2/OIDC) can override this to do so.
     * A no-op by default.
     */
    default void onUnauthorized(ClientRequestContext requestContext) {
    }

}
