quarkus.openapi-generator.codegen.spec.name_mappings_testing_yml.name-mappings._type=customType
quarkus.openapi-generator.codegen.spec.name_mappings_testing_yml.base-package=org.acme.openapi.namemapping

quarkus.keycloak.devservices.enabled=false
