quarkus.openapi-generator.codegen.spec.name_mappings_testing_yml.base-package=org.acme.openapi.animals
quarkus.openapi-generator.codegen.spec.name_mappings_testing_yml.name-mappings.born=bornDate
quarkus.openapi-generator.codegen.spec.name_mappings_testing_yml.name-mappings.deceased=deathDate

quarkus.keycloak.devservices.enabled=false