name: Feature Request
description: Request a new feature
labels: ["type: feature"]
body:

  - type: markdown
    attributes:
      value: |
        :pray: Thanks for taking the time to fill out this feature request!

  - type: markdown
    attributes:
      value: |
        ## Feature Request

  - type: dropdown
    id: extension
    attributes:
      label: "Tell us the extension to which you'd like to add the feature."
      multiple: false
      options:
        - Client
        - Server
        - Mock
    validations:
      required: true

  - type: textarea
    id: what-would-you-like-to-add
    attributes:
      label: "What kind of feature would you like to add?"
      placeholder: "Description of the feature you'd like to see."
    validations:
      required: true

  - type: textarea
    id: proposals
    attributes:
      label: "Proposal(s):"
      placeholder: "Describe your proposal(s) and any relevant details here."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternative(s):"
      placeholder: "Describe any alternative approaches, options, or suggestions you’d like to consider."

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional info:"
      placeholder: "Provide any supplementary details, context, or supporting information here."

  - type: textarea
    attributes:
      label: Community Notes
      value: |
        <!-- Please keep this note for the community -->
        * Please vote by adding a 👍 reaction to the feature to help us prioritize.
        * If you want to work on this feature, please leave a comment.