= Quarkus - OpenAPI Generator - Client

include::./includes/attributes.adoc[]
:extension-status: preview

This extension is for REST code generation for client side only. If you're looking for code generation for the server side, please take a look at the xref:server.adoc[Quarkus OpenAPI Generator Server Extension].

include::./includes/want-to-contribute.adoc[]

[[getting-started]]
== Getting Started

include::./includes/getting-started.adoc[leveloffset=+1, opts=optional]

[[resteasy-support]]
== RESTEasy Reactive and Classic support

include::./includes/resteasy-support.adoc[leveloffset=+1, opts=optional]

[[returning-response-objects]]
== Returning `Response` objects

include::./includes/return-response-objects.adoc[leveloffset=+1, opts=optional]

[[logging]]
== Logging

include::./includes/logging.adoc[leveloffset=+1, opts=optional]

[[filter-openapi-spec-files]]
== Filtering OpenAPI Specification Files

include::./includes/filter-openapi-spec-files.adoc[leveloffset=+1, opts=optional]

[[authentication-support]]
== Authentication Support

include::./includes/authentication-support.adoc[leveloffset=+1, opts=optional]

[[autorization-token-prop]]
== Authorization Token Propagation

include::./includes/authorization-token-propagation.adoc[leveloffset=+1, opts=optional]

[[circuit-breaker]]
== Circuit Breaker

include::./includes/circuit-breaker.adoc[leveloffset=+1, opts=optional]

[[sending-multipart-formdata]]
== Sending multipart/form-data

include::./includes/sending-multipart-formdata.adoc[leveloffset=+1, opts=optional]

[[Supporting-unexpected-enums-values]]
== Supporting unexpected Enum values

include::./includes/supporting-unexpected-enums-values.adoc[leveloffset=+1, opts=optional]

== Generating files via InputStream

Having the files in the `src/main/openapi` directory will generate the REST stubs by default. Alternatively, you can implement
the `io.quarkiverse.openapi.generator.deployment.codegen.OpenApiSpecInputProvider`
interface to provide a list of `InputStream`s of OpenAPI specification files. This is useful in scenarios where you want to dynamically generate the client code without having the target spec file
saved locally in your project.

See the example implementation https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/integration-tests/generation-input/src/main/java/io/quarkiverse/openapi/generator/codegen/ClassPathPetstoreOpenApiSpecInputProvider.java[here]

== Skip Deprecated Attributes in Model classes

The domain objects are classes generated in the `model` package. These classes might have https://spec.openapis.org/oas/v3.1.0#fixed-fields-9[deprecated attributes] in the Open API specification
file. By default, these attributes are generated. You can fine tune this behavior if the deprecated attributes should not be generated.

Use the property key `<base_package>.model.MyClass.generateDeprecated=false` to disable the deprecated attributes in the given model. For example `org.acme.weather.Country.generatedDeprecated=false`.

== Skip Deprecated Operations in API classes

The client objects are classes generated in the `api` package. These classes might have https://spec.openapis.org/oas/v3.1.0#operation-object[deprecated operations] in the Open API specification
file. By default, these operations are generated. You can fine tune this behavior if the deprecated operations should not be generated.

Use the property key `<base_package>.api.MyClass.generateDeprecated=false` to disable the deprecated operations in the given API. For example `org.acme.openapi.simple.api.DefaultApi.generatedDeprecated=false`.

[source,java]
----
package org.acme.openapi.simple.api;

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.MediaType;

@Path("")
@RegisterRestClient(configKey="simple-openapi_json")
@RegisterProvider(org.test.Foo.class)
@RegisterProvider(org.test.Bar.class)
public interface DefaultApi {

    @GET
    @Path("/bye")
    @Produces({ "text/plain" })
    @org.eclipse.microprofile.faulttolerance.CircuitBreaker
    public String byeGet();
}
----

See the module `integration-tests/register-provider` for an example of how to use this feature.

== Skip OpenAPI schema validation

Use the property key `quarkus.openapi-generator.codegen.validateSpec=false` to disable validating the input specification file before code generation. By default, invalid specifications will result in an error.

== Type, schema and import mappings

It's possible to remap types in the generated files. For example, instead of a `File` you can configure the code generator to use `InputStream` for all file upload parts of multipart request, or you could change all `UUID` types to `String`. You can configure this in your `application.properties` using the following configuration keys:

[%autowidth]
|===
|Description |Property Key |Example

|Type Mapping
|`quarkus.openapi-generator.codegen.spec.[filename].type-mappings.[oas_type]`
|`quarkus.openapi-generator.codegen.spec.my_spec_yml.type-mappings.File=InputStream` will use `InputStream` as type for all objects of the OAS File type.
|Import Mapping
|`quarkus.openapi-generator.codegen.spec.[filename].import-mappings.[type]`
|`quarkus.openapi-generator.codegen.spec.my_spec_yml.import-mappings.File=java.io.InputStream` will replace the default `import java.io.File` with `import java.io.InputStream`
|Schema Mapping
|`quarkus.openapi-generator.codegen.spec.[filename].schema-mappings.[type]`
|`quarkus.openapi-generator.codegen.spec.my_spec_yml.schema-mappings.YearMonth=java.time.YearMonth` will use `java.time.YearMonth` as type for all schemas of the chosen type in the file.
|===

Note that these configuration properties are maps. For the type-mapping the keys are OAS data types and the values are Java types.

Another common example is needing `java.time.Instant` as type for date-time fields in your POJO classes. You can achieve with these settings:

[source,properties]
----
quarkus.openapi-generator.codegen.spec.my_spec_yml.type-mappings.DateTime=Instant
quarkus.openapi-generator.codegen.spec.my_spec_yml.import-mappings.Instant=java.time.Instant
----

It's also possible to only use a type mapping with a fully qualified name, for instance `quarkus.openapi-generator.codegen.spec.my_spec_yml.type-mappings.File=java.io.InputStream`. For more information and a list of all types see the OpenAPI generator documentation on https://openapi-generator.tech/docs/usage/#type-mappings-and-import-mappings[Type Mappings and Import Mappings] and https://openapi-generator.tech/docs/customization#schema-mapping[Schema mapping].

See the module https://github.com/quarkiverse/quarkus-openapi-generator/tree/main/integration-tests/type-mapping[type-mapping] for an example of how to use this feature.

[[config-key]]
== Config key

include::./includes/config-key.adoc[leveloffset=+1, opts=optional]

[[template-customization]]
== Template Customization

include::./includes/template-customization.adoc[leveloffset=+1, opts=optional]

[[additional-properties]]
== Additional Properties as Attribute

include::./includes/additional-properties-as-attribute.adoc[leveloffset=+1, opts=optional]

[[additional-request-args]]
== Add Additional Request Arguments to each API Method

include::./includes/additional-request-args.adoc[leveloffset=+1, opts=optional]

[[use-bean-validation]]
== Add Bean Validation support to every API method and validation annotations to all models

include::./includes/bean-validation.adoc[leveloffset=+1, opts=optional]

[[generate-apis]]
== Generate APIs

include::./includes/generate-apis.adoc[leveloffset=+1, opts=optional]

[[generate-models]]
== Generate Models

include::./includes/generate-models.adoc[leveloffset=+1, opts=optional]

== Known Limitations

=== Supported Arguments

Currently not all arguments are supported by this extension

*supported:*

* Body
* https://javadoc.io/doc/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs/jakarta/ws/rs/Path.html[@PathParams]
* https://javadoc.io/doc/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs/jakarta/ws/rs/RestQuery.html[@QueryParams]
* https://javadoc.io/doc/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs/jakarta/ws/rs/FormParam.html[@FormParams]
* https://javadoc.io/doc/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs/jakarta/ws/rs/CookieParam.html[@CookieParam]
* https://javadoc.io/doc/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs/jakarta/ws/rs/HeaderParam.html[@HeaderParam]

*unsupported:*

* https://javadoc.io/doc/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs/jakarta/ws/rs/MatrixParam.html[@MatrixParam]


(You can extend all endpoints with `additional-request-args`)

These are the known limitations of this pre-release version:

* Only Jackson support

We will work in the next few releases to address these use cases, until there please provide feedback for the current state of this extension. We also love contributions icon:heart[1x,role=red].