= Quarkus - OpenAPI Generator - Server with OpenAPITools

include::./includes/attributes.adoc[]

This documentation helps you to use Quarkus OpenAPI Generator Server with the OpenAPITools code generator.
To see how to use with Apicurio, please see the xref:apicurio.adoc[Apicurio] documentation.

:extension-status: preview

Add the following dependency to your project's `pom.xml` file:

[source,xml]
----
<dependency>
  <groupId>io.quarkiverse.openapi.generator</groupId>
  <artifactId>quarkus-openapi-generator-server</artifactId>
  <version>{project-version}</version>
</dependency>
----

You will also need to add or update the `quarkus-maven-plugin` configuration with the following:

WARNING: You probably already have this configuration if you created your application with https://code.quarkus.io/[Code Quarkus]. That said, double-check your configuration not to add another `plugin` entry.

[source,xml]
----
<plugin>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-maven-plugin</artifactId>
  <extensions>true</extensions>
  <executions>
    <execution>
      <goals>
        <goal>build</goal>
        <goal>generate-code</goal>
        <goal>generate-code-tests</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

[IMPORTANT]
====
To use the OpenAPITools code generator, you need to configure your `application.properties` as follow:

[source,properties]
----
quarkus.openapi.generator.server.use=openapitools
----
====

Now, create the directory `openapi` under your `src/main/resources` path and add the OpenAPI spec files there. We support JSON, YAML and YML extensions.

All OpenAPI specification files found in the input base directory are automatically discovered and generated. You can explicitly configure a spec with the following property:

[source,properties]
----
quarkus.openapi.generator.server.spec=petstore-openapi.json
----

[TIP]
====
If no explicit specification is configured, the extension generates code for all OpenAPI files in the input base directory using default values. When using per-spec configuration (`quarkus.openapi.generator.server.spec.<id>.*`), any unconfigured spec files are also auto-discovered and generated with defaults.
====

[NOTE]
====
You can see the `petstore-openapi.json` file through this https://raw.githubusercontent.com/quarkiverse/quarkus-openapi-generator/refs/heads/main/server/integration-tests/reactive/src/main/resources/openapi/petstore-openapi.json[link].
====

If you want to change the directory where OpenAPI files must be found, use the property `quarkus.openapi.server.input-base-dir`.

[IMPORTANT]
====
It is relative to the project base directory. For example, if you have a project called `MyJavaProject` and decide to place them in `MyJavaProject/openapi-definitions`, use the following property:
====

[source,properties]
----
quarkus.openapi.generator.server.input-base-dir=openapi-definitions
----

If a base package name is not provided, it will be used the default `org.acme`. You can customize it with the following property:

[source,properties]
----
quarkus.openapi.generator.server.base-package=io.petstore
----

== Multi-file specifications

OpenAPITools can generate from entry specs that use relative `$ref` values across multiple YAML or JSON files. Place the full spec tree under the configured input base directory and point the generator at the entry document.

For example:

[source,properties]
----
quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.input-base-dir=src/main/resources/openapi
quarkus.openapi.generator.server.spec=module1.yaml
----

If `module1.yaml` contains `$ref: './common/common-spec.yaml#/components/schemas/CommonPet'`, the referenced file is resolved automatically as long as `common/common-spec.yaml` is present under the same base directory.

== Multiple generated servers

You can generate more than one server stub in the same build by configuring one block per spec:

[source,properties]
----
quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.spec.petstore_openapi_json.base-package=org.acme.api.petstore
quarkus.openapi.generator.server.spec.simple_server_yaml.base-package=org.acme.api.animals
----

The identifier after `server.spec.` may also be an alias when you want to point explicitly to a file or override its input directory:

[source,properties]
----
quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.spec.petstore.spec=petstore-openapi.json
quarkus.openapi.generator.server.spec.petstore.base-package=org.acme.api.petstore
quarkus.openapi.generator.server.spec.animals.input-base-dir=src/main/resources/other-openapi
quarkus.openapi.generator.server.spec.animals.spec=animals.yaml
quarkus.openapi.generator.server.spec.animals.base-package=org.acme.api.animals
----

Properties defined under `quarkus.openapi.generator.server.spec.<id>.*` override the global `server.*` values for that specific generated server.

== Filtering auto-discovered specifications

When using per-spec configuration or when no specification is explicitly configured, the extension auto-discovers all OpenAPI files in the input base directory. You can filter which files are processed using the `include` and `exclude` properties:

[source,properties]
----
quarkus.openapi.generator.server.include=petstore-openapi.json,simple-server.yaml
----

or

[source,properties]
----
quarkus.openapi.generator.server.exclude=common-spec.yaml,shared-models.yaml
----

The `include` and `exclude` properties match against file names only (not full paths). When `include` is set, only the listed files are processed. When `exclude` is set, the listed files are skipped. Both can be used together.

By default, the extension generates non-reactive code. If you would like to change it, you can do it as follows:

[source,properties]
----
quarkus.openapi.generator.server.use-reactive=true
----

== Returning Response Objects

By default, the generator uses the model class or `void` as the return type for operations. If you need more control over the response, such as setting custom headers or status codes (e.g., `201 Created`), you can enable the use of `org.jboss.resteasy.reactive.RestResponse`:

[NOTE]
====
This property only applies when using the OpenAPITools code generator (i.e., when `quarkus.openapi.generator.server.use` is set to `openapitools`).
====

[source,properties]
----
quarkus.openapi.generator.server.use-rest-response=true
----

You can also configure this at the operation level by using one of the following vendor extensions:
* `x-return-type: org.jboss.resteasy.reactive.RestResponse` (must be fully qualified)
* `x-use-rest-response: true`

[source,yaml]
----
paths:
  /pet:
    post:
      operationId: createPet
      x-return-type: org.jboss.resteasy.reactive.RestResponse
      # Alternatively:
      # x-use-rest-response: true
      responses:
        "201":
          description: Created
----

When enabled globally or at the operation level, the generated methods will look like this:

[source,java]
----
public org.jboss.resteasy.reactive.RestResponse<Pet> createPet(Pet request);
----

If you combine it with `use-reactive=true`, the return type will be:

[source,java]
----
public Uni<org.jboss.resteasy.reactive.RestResponse<Pet>> createPet(Pet request);
----

Run `mvn compile` to generate your classes in `target/generated-sources/quarkus-openapi-generator-server` path:

[source]
----
- io.petstore
  - model
    - Address.java
    - ApiResponse.java
    - Category.java
    - Customer.java
    - Order.java
    - Pet.java
    - Tag.java
    - User.java
  - resources
    - PetResource.java
    - StoreResource.java
    - UserResource.java
----

You can reference the generated code in your project, for example:

[source,java]
----
include::{examples-dir}/server/DefaultPetResource.java[tag=content]
----

See the https://github.com/quarkiverse/quarkus-openapi-generator/tree/main/server/integration-tests[integration-tests] module for more information of how to use this extension. Please be advised that the extension is on experimental, early development stage.

== `x-smallrye-profile-<profileName>`

You can add [SmallRye profile-specific vendor extensions](https://github.com/smallrye/smallrye-open-api?tab=readme-ov-file#x-smallrye-profile-profilename) directly to an OpenAPI operation, and the OpenAPITools server generator will propagate them to the generated resource method.

You must add the dependency below to your project, as the `org.eclipse.microprofile.openapi.annotations.*` annotations are required at compile time. Without it, the generated code will not compile:

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-openapi</artifactId>
</dependency>
----

When one or more `x-smallrye-profile-<profileName>` entries are present on an operation, the generated method is annotated with `@org.eclipse.microprofile.openapi.annotations.extensions.Extensions` and one `@Extension` entry per matching vendor extension.

Example:

[source,yaml]
----
paths:
  /pet/findByTags:
    get:
      operationId: findPetsByTags
      x-smallrye-profile-admin: ""
      x-smallrye-profile-order: ""
      x-smallrye-profile-user: ""
----

This generates an annotation similar to:

[source,java]
----
@org.eclipse.microprofile.openapi.annotations.extensions.Extensions({
    @org.eclipse.microprofile.openapi.annotations.extensions.Extension(name = "x-smallrye-profile-admin", value = ""),
    @org.eclipse.microprofile.openapi.annotations.extensions.Extension(name = "x-smallrye-profile-order", value = ""),
    @org.eclipse.microprofile.openapi.annotations.extensions.Extension(name = "x-smallrye-profile-user", value = "")
})
----

The generated entries are sorted by profile name to keep the output deterministic.

== Configuration Properties

include::./includes/quarkus-openapi-generator-server.adoc[opts=optional, leveloffset=+1]
