---
openapi: 3.0.3
info:
  title: token-propagation-external-service1 API
  version: 3.0.0-lts-SNAPSHOT
paths:
  /token-propagation-external-service1/executeQuery1:
    post:
      operationId: executeQuery1
      responses:
        "200":
          description: OK
      security:
        - service1-http-bearer: []
components:
  securitySchemes:
    service1-http-bearer:
      type: http
      scheme: bearer