---
openapi: 3.0.3
info:
  title: external-service4 API
  version: 3.0.0-SNAPSHOT
paths:
  /token-propagation-external-service4/executeQuery4:
    post:
      operationId: executeQuery4
      responses:
        "200":
          description: OK
      security:
        - service4-oauth2: []
components:
  securitySchemes:
    service4-oauth2:
        type: oauth2
        flows:
          clientCredentials:
            authorizationUrl: https://example.com/oauth
            tokenUrl: https://example.com/oauth/token
            scopes: {}