---
openapi: 3.0.3
info:
  title: external-service5 API
  version: 3.0.0-SNAPSHOT
paths:
  /token-propagation-external-service5/executeQuery5:
    post:
      operationId: executeQuery5
      responses:
        "200":
          description: OK
      security:
        - service5-oauth2: []
components:
  securitySchemes:
    service5-oauth2:
        type: oauth2
        flows:
          clientCredentials:
            authorizationUrl: https://example.com/oauth
            tokenUrl: https://example.com/oauth/token
            scopes: {}