---
openapi: 3.0.3
info:
  title: token-propagation-external-service3 API
  version: 3.0.0-SNAPSHOT
paths:
  /token-propagation-external-service3/executeQuery3:
    post:
      operationId: executeQuery3
      responses:
        "200":
          description: OK
      security:
        - service3-http-bearer: []
components:
  securitySchemes:
    service3-http-bearer:
      type: http
      scheme: bearer