quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.spec=openapi.yaml
quarkus.openapi.generator.server.input-base-dir=src/main/server

quarkus.openapi-generator.codegen.input-base-dir=src/main/client