quarkus.openapi.generator.spec=petstore-openapi.json
quarkus.openapi.generator.base-package=io.petstore
quarkus.openapi.generator.reactive=false
quarkus.openapi.generator.builders=true

quarkus.openapi.generator.server.operation-ids.findPetsByStatus.return-type=org.jboss.resteasy.reactive.RestResponse