quarkus.openapi-generator.codegen.spec.multipart_client_form_yml.base-package=org.acme.openapi.multipart.clientform
quarkus.openapi-generator.codegen.spec.multipart_client_form_yml.additional-model-type-annotations=@io.quarkus.runtime.annotations.RegisterForReflection
# Enable ClientMultipartForm for RESTEasy Reactive
quarkus.openapi-generator.codegen.spec.multipart_client_form_yml.resteasy-reactive-client-form=true

quarkus.keycloak.devservices.enabled=false

